### PR TITLE
Update scene.mess: typo sequences: -> sequence:

### PR DESCRIPTION
**Pull request by greenfork**

### CODE REVIEW

**Comment by Shinmera** [comment]
What the `org.shirakumo.trivial-extensible-sequences` package is locally nicknamed to is up to you, and for trial's internal sources it *is* named `sequences`. This is not a bug.

**Comment by greenfork** [comment]
Alright, thanks!

I didn't use any nicknames, just loaded the standard template from the getting started example https://shirakumo.github.io/trial/start.html

**Comment by Shinmera** [comment]
If your implementation provides a `sequence` package then that's what your implementation happens to do, not a universal standard.

**Comment by greenfork** [comment]
I didn't know it is sbcl-specific, I looked it up, that is true. Thank you for explaining

**Comment by Shinmera** [comment]
I've added the nickname to the start guide as well to avoid confusion in the future.

**Pull request closed without merging**
